version: '3'
# Creating 3 instance of the Node server
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      - APP_NAME=App2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    ports:
      - "3003:3000"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mounting the nginx.conf file to the container
    depends_on:
      - app1
      - app2
      - app3
